apiVersion: v1
kind: Service
metadata:
  name: tusd-svc
  labels:
    app: tusd
spec:
  ports:
  - name: tus
    port: 1080
    targetPort: 1080
  selector:
    app: tusd
    type: web
  type: NodePort
