apiVersion: v2
name: tator
version: 0.0.1
kubeVersion: ">=1.14.3-r0"
description: "A web application for video hosting, annotation, and algorithm deployment."
type: application
home: https://github.com/cvisionai/tator
sources:
  - https://github.com/cvisionai/tator
dependencies:
  - name: metrics-server
    version: 5.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: metrics-server.enabled
  - name: metallb
    version: 0.1.21
    repository: https://charts.bitnami.com/bitnami
    condition: metallb.enabled
  - name: redis
    version: 12.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: 7.4.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: filebeat
    version: 7.4.1
    repository: https://helm.elastic.co
    condition: filebeat.enabled
  - name: kibana
    version: 7.4.1
    repository: https://helm.elastic.co
    condition: kibana.enabled
maintainers:
  - name: CVision AI
    email: info@cvisionai.com
    url: www.cvisionai.com
engine: gotpl
icon: https://raw.githubusercontent.com/cvisionai/tator/master/main/static/images/cvision-logo-svg.svg
