apiVersion: v2
name: tator
version: 0.1.1
kubeVersion: ">=1.14.3-r0"
description: "A web application for video hosting, annotation, and algorithm deployment."
type: application
home: https://github.com/cvisionai/tator
sources:
  - https://github.com/cvisionai/tator
dependencies:
  - name: metallb
    version: 3.0.7
    repository: https://charts.bitnami.com/bitnami
    condition: metallb.enabled
  - name: redis
    version: 16.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: filebeat
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: filebeat.enabled
  - name: kibana
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: minio
    version: 8.0.8
    repository: https://helm.min.io
    condition: minio.enabled
  - name: kube-prometheus-stack
    version: 36.2.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
  - name: prometheus-adapter
    version: 2.12.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-adapter.enabled
  - name: prometheus-statsd-exporter
    version: 0.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-statsd-exporter.enabled
maintainers:
  - name: CVision AI
    email: info@cvisionai.com
    url: www.cvisionai.com
engine: gotpl
icon: https://raw.githubusercontent.com/cvisionai/tator/master/main/static/images/tator-logo-symbol-only.png
