apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app: graphql
    type: web
spec:
  selector:
    matchLabels:
      app: graphql
      type: web
  replicas: 1
  template:
    metadata:
      labels:
        app: graphql
        type: web
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
        webServer: "yes"
      containers:
        - name: tator-graphql
          image: {{ .Values.dockerRegistry }}/tator_graphql:{{ .Values.gitRevision }}
          imagePullPolicy: "Always"
          command:
          - openapi-to-graphql
          args:
          - /schema.yaml
          - --cors
          - --operatonIdFieldNames
          resources:
            limits:
              cpu: {{ .Values.graphqlCpuLimit | default "4000m" }}
              memory: {{ .Values.graphqlMemoryLimit | default "16Gi" }}
            requests:
              cpu: {{ .Values.graphqlCpuRequest | default "1000m" }}
              memory: {{ .Values.graphqlMemoryRequest | default "4Gi" }}
          env:
            - name: DEBUG
              value: "preprocessing,translation,http"
          ports:
            - containerPort: 3000
              name: graphql
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-svc
  labels:
    app: graphql
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: graphql-port
  selector:
    app: graphql
    type: web
  type: NodePort
