apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  minReplicas: {{ .Values.hpa.nginxMinReplicas }}
  maxReplicas: {{ .Values.hpa.nginxMaxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: {{ .Values.hpa.nginxCpuPercent }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gunicorn-hpa
spec:
  minReplicas: {{ .Values.hpa.gunicornMinReplicas }}
  maxReplicas: {{ .Values.hpa.gunicornMaxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gunicorn-deployment
  targetCPUUtilizationPercentage: {{ .Values.hpa.gunicornCpuPercent }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tusd-hpa
spec:
  minReplicas: {{ .Values.hpa.tusdMinReplicas }}
  maxReplicas: {{ .Values.hpa.tusdMaxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tusd-deployment
  targetCPUUtilizationPercentage: {{ .Values.hpa.tusdCpuPercent }}
