apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-internal-deployment
spec:
  selector:
    matchLabels:
      app: nginx-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-internal
      annotations:
        checksum/cm: {{ include (print $.Template.BasePath "/nginx-internal-conf.yaml") . | sha256sum }}
        checksum/tusdproxy: {{ include (print $.Template.BasePath "/_tusdProxy.tpl") . | sha256sum }}
    spec:
      {{- if .Values.awsFargate.enabled }}
      {{- else }}
      nodeSelector:
        webServer: "yes"
      {{- end }}
      containers:
        - name: nginx
          image: nginx:1.19.2
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 4000m
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
              name: nginx-internal-conf
            {{ include "volumeMounts.template" . | indent 12 }}
      volumes:
        - name: nginx-internal-conf
          configMap:
            name: nginx-internal-conf
        {{ include "volumes.template" . | indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-internal
  type: NodePort
