apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{ .Values.hpa.nginxMinReplicas }}
  template:
    metadata:
      labels:
        app: nginx
      # Force nginx update whenever this file changes.
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
{{ if .Values.awsFargate.enabled }}
{{ else }}
      nodeSelector:
        webServer: "yes"
{{ end }}
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 4000m
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
              name: nginx-conf
            - mountPath: /ssl/{{ .Values.tlsCertFile | default signed_chain.crt }}
              subPath: {{ .Values.tlsCertFile | default signed_chain.crt }}
              readOnly: true
              name: {{ .Values.tlsCertSecretName | default tls-cert }}
            - mountPath: /ssl/{{ .Values.tlsKeyFile | default domain.key }}
              subPath: {{ .Values.tlsKeyFile | default domain.key }}
              readOnly: true
              name: {{ .Values.tlsKeySecretName | default tls-key }}
            {{- if hasKey .Values "redirects" }}
            {{- range .Values.redirects }}
            - mountPath: /ssl/{{ .tlsCertFile }}
              subPath: {{ .tlsCertFile }}
              readOnly: true
              name: {{ .tlsCertSecretName }}
            - mountPath: /ssl/{{ .tlsKeyFile }}
              subPath: {{ .tlsKeyFile }}
              readOnly: true
              name: {{ .tlsKeySecretName }}
            {{- end }}
            {{- end }}
            - mountPath: /data/static
              name: main-pv-claim
              subPath: static
            - mountPath: /data/media
              name: main-pv-claim
              subPath: media
            - mountPath: /data/raw
              name: main-pv-claim
              subPath: raw
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: {{ .Values.tlsCertSecretName | default tls-cert }}
          secret:
            secretName: {{ .Values.tlsCertSecretName | default tls-cert }}
            items:
              - key: {{ .Values.tlsCertFile | default signed_chain.crt }}
                path: {{ .Values.tlsCertFile | default signed_chain.crt }}
        - name: {{ .Values.tlsKeySecretName | default tls-key }}
          secret:
            secretName: {{ .Values.tlsKeySecretName | default tls-key }}
            items:
              - key: {{ .Values.tlsKeyFile | default domain.key }}
                path: {{ .Values.tlsKeyFile | default domain.key }}
        {{- if hasKey .Values "redirects" }}
        {{- range .Values.redirects }}
        - name: {{ .tlsCertSecretName }}
          secret:
            secretName: {{ .tlsCertSecretName }}
            items:
              - key: {{ .tlsCertFile }}
                path: {{ .tlsCertFile }}
        - name: {{ .tlsKeySecretName }}
          secret:
            secretName: {{ .tlsKeySecretName }}
            items:
              - key: {{ .tlsKeyFile }}
                path: {{ .tlsKeyFile }}
        {{- end }}
        {{- end }}
        - name: main-pv-claim
          persistentVolumeClaim:
            claimName: main-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
{{- if .Values.metallb.enabled }}
  annotations:
    metallb.universe.tf/address-pool: my-ip-space
{{- else }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
{{- end }}
spec:
{{- if .Values.metallb.enabled }}
  loadBalancerIP: {{ .Values.metallb.loadBalancerIp }}
{{- end }}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer
