kind: PersistentVolume
apiVersion: v1
metadata:
  name: main-pv
spec:
  capacity:
    storage: {{ .Values.pvc.size | default "10Ti" }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: main-pv-claim
  {{- if .Values.awsStorage.enabled }}
  volumeMode: Filesystem
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.pv.filesystemId }}
  {{- else }}
  mountOptions:
    {{- range .Values.pv.nfsMountOptions }}
    - {{ . }}
    {{- end }}
  nfs:
    server: {{ .Values.pv.nfsServer }}
    path: {{ .Values.pv.path }}
  {{- end }} # .Values.awsStorage.enabled
{{- range .Values.pv.mediaShards }}
{{- $settings := dict "Values" $.Values "shard" . }}
{{ include "shard.pv" $settings }}
{{- end }}
---
{{ if .Values.elasticsearch.enabled }}
{{ if .Values.elasticsearch.persistence.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: {{ $.Values.elasticsearch.volumeClaimTemplate.resources.requests.storage }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: elasticsearch-master-elasticsearch-master-0
  hostPath:
    path: {{ $.Values.elasticsearch.hostPath }}
{{ end }}
{{ end }}
---
{{ if .Values.postgis.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgis-pv
spec:
  capacity:
    storage: {{ $.Values.postgis.persistence.size }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: postgis-pv-claim
  hostPath:
    path: {{ $.Values.postgis.hostPath }}
{{ end }}
