kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: main-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "10Ti" }}
---
{{ if .Values.staticPv.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "10Ti" }}
{{ end }}
{{ if hasKey .Values.postgis "hostPath" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgis-pv-claim
  labels:
    app: postgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgis.persistence.size }}
{{ end }}
