{{- if hasKey .Values.pv "uploadShards" }}
{{- range .Values.pv.uploadShards }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd-{{ .name }}-deployment
  labels:
    app: tusd
    type: web
spec:
  selector:
    matchLabels:
      app: tusd-{{ .name }}
      type: web
  template:
    metadata:
      labels:
        app: tusd-{{ .name }}
        type: web
        role: uploader
    spec:
      {{- if $.Values.awsFargate.enabled }}
      {{- else }}
      nodeSelector:
        webServer: "yes"
      {{- end }}
      containers:
        - name: tusd-{{ .name }}
          image: {{ $.Values.dockerRegistry }}/tator_tusd
          command: ["tusd"]
          args: ["-behind-proxy", "-upload-dir", "/{{ .name }}"]
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 500Mi
          ports:
            - containerPort: 1080
          volumeMounts:
            - mountPath: /{{ .name }}
              name: {{ .name }}-pv-claim
      volumes:
        - name: {{ .name }}-pv-claim
          persistentVolumeClaim:
            claimName: {{ .name }}-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tusd-{{ .name }}-svc
  labels:
    app: tusd-{{ .name }}
spec:
  ports:
  - name: tus-{{ .name }}
    port: 1080
    targetPort: 1080
  selector:
    app: tusd-{{ .name }}
    type: web
  type: NodePort
---
{{- end }}
{{- else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tusd-deployment
  labels:
    app: tusd
    type: web
spec:
  selector:
    matchLabels:
      app: tusd
      type: web
  template:
    metadata:
      labels:
        app: tusd
        type: web
    spec:
      {{- if .Values.awsFargate.enabled }}
      {{- else }}
      nodeSelector:
        webServer: "yes"
      {{- end }}
      containers:
        - name: tusd
          image: {{ .Values.dockerRegistry }}/tator_tusd
          command: ["tusd"]
          args: ["-behind-proxy", "-upload-dir", "/uploads"]
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 500Mi
          ports:
            - containerPort: 1080
          volumeMounts:
            - mountPath: /uploads
              name: main-pv-claim
              subPath: upload
      volumes:
        - name: main-pv-claim
          persistentVolumeClaim:
            claimName: main-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tusd-svc
  labels:
    app: tusd
spec:
  ports:
  - name: tus
    port: 1080
    targetPort: 1080
  selector:
    app: tusd
    type: web
  type: NodePort
{{- end }}
